// SPDX-License-Identifier: LCL-1.0
// Copyright (c) 2025 Markus Maiwald

//! Git Hooks Integration
//!
//! Generates and manages git hooks that integrate with ProGit's issue tracking.
//! The commit-msg hook parses commit messages for issue references and
//! automatically updates issue status.
//!
//! Keywords:
//! - `closes #123`, `fixes #123`, `resolves #123` -> marks issue as Done
//! - `refs #123`, `see #123`, `re #123` -> marks issue as In Progress
//! - `#123` (bare reference) -> no status change, just links

use anyhow::Result;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// Hook types supported by ProGit
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HookType {
    CommitMsg,
    PreCommit,
    PostCommit,
}

impl HookType {
    pub fn filename(&self) -> &'static str {
        match self {
            HookType::CommitMsg => "commit-msg",
            HookType::PreCommit => "pre-commit",
            HookType::PostCommit => "post-commit",
        }
    }
}

/// Install ProGit hooks in a repository
pub fn install_hooks(repo_root: &Path) -> Result<Vec<HookType>> {
    let hooks_dir = repo_root.join(".git").join("hooks");

    if !hooks_dir.exists() {
        return Err(anyhow::anyhow!(
            "Not a git repository (no .git/hooks directory)"
        ));
    }

    let mut installed = Vec::new();

    // Install commit-msg hook
    let hook_path = hooks_dir.join("commit-msg");
    let hook_content = generate_commit_msg_hook();

    // Check if hook already exists
    if hook_path.exists() {
        let existing = fs::read_to_string(&hook_path)?;
        if existing.contains("PROGIT_HOOK") {
            // Already installed, update it
            fs::write(&hook_path, &hook_content)?;
        } else {
            // User has custom hook, prepend our hook
            let combined = format!("{}\n\n# Original hook below:\n{}", hook_content, existing);
            fs::write(&hook_path, combined)?;
        }
    } else {
        fs::write(&hook_path, &hook_content)?;
    }

    // Make executable
    let mut perms = fs::metadata(&hook_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&hook_path, perms)?;

    installed.push(HookType::CommitMsg);

    Ok(installed)
}

/// Uninstall ProGit hooks from a repository
pub fn uninstall_hooks(repo_root: &Path) -> Result<Vec<HookType>> {
    let hooks_dir = repo_root.join(".git").join("hooks");

    if !hooks_dir.exists() {
        return Err(anyhow::anyhow!(
            "Not a git repository (no .git/hooks directory)"
        ));
    }

    let mut uninstalled = Vec::new();

    let hook_path = hooks_dir.join("commit-msg");
    if hook_path.exists() {
        let content = fs::read_to_string(&hook_path)?;
        if content.contains("PROGIT_HOOK") {
            // Check if there's user content after our hook
            if let Some(idx) = content.find("# Original hook below:") {
                // Restore original hook
                let original = content[idx + "# Original hook below:".len()..].trim();
                if !original.is_empty() {
                    fs::write(&hook_path, original)?;
                } else {
                    fs::remove_file(&hook_path)?;
                }
            } else {
                fs::remove_file(&hook_path)?;
            }
            uninstalled.push(HookType::CommitMsg);
        }
    }

    Ok(uninstalled)
}

/// Check if hooks are installed
pub fn hooks_status(repo_root: &Path) -> Result<Vec<(HookType, bool)>> {
    let hooks_dir = repo_root.join(".git").join("hooks");

    if !hooks_dir.exists() {
        return Err(anyhow::anyhow!("Not a git repository"));
    }

    let mut status = Vec::new();

    let hook_path = hooks_dir.join("commit-msg");
    let installed = if hook_path.exists() {
        let content = fs::read_to_string(&hook_path).unwrap_or_default();
        content.contains("PROGIT_HOOK")
    } else {
        false
    };
    status.push((HookType::CommitMsg, installed));

    Ok(status)
}

/// Generate the commit-msg hook script
fn generate_commit_msg_hook() -> String {
    r#"#!/bin/sh
# PROGIT_HOOK: Auto-generated by ProGit - Do not edit manually
# This hook updates issue status based on commit message references
#
# Keywords:
#   closes/fixes/resolves #ID -> Done
#   refs/see/re #ID -> In Progress
#   #ID (bare) -> No change, just link

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Find prog binary
PROG_BIN=$(which prog 2>/dev/null || echo "./target/debug/prog")

# Check if prog is available
if ! command -v "$PROG_BIN" &> /dev/null && [ ! -x "$PROG_BIN" ]; then
    # Silently skip if prog not found
    exit 0
fi

# Extract issue references and process them
# Pattern: (closes|fixes|resolves|refs|see|re)?\s*#(\d+|[a-zA-Z0-9-]+)

# Process "closes/fixes/resolves" -> mark as done
echo "$COMMIT_MSG" | grep -oiE '(closes?|fix(es)?|resolves?)\s*#[a-zA-Z0-9-]+' | while read -r match; do
    ISSUE_ID=$(echo "$match" | grep -oE '#[a-zA-Z0-9-]+' | tr -d '#')
    if [ -n "$ISSUE_ID" ]; then
        "$PROG_BIN" issue status "$ISSUE_ID" done 2>/dev/null || true
    fi
done

# Process "refs/see/re" -> mark as in-progress
echo "$COMMIT_MSG" | grep -oiE '(refs?|see|re)\s*#[a-zA-Z0-9-]+' | while read -r match; do
    ISSUE_ID=$(echo "$match" | grep -oE '#[a-zA-Z0-9-]+' | tr -d '#')
    if [ -n "$ISSUE_ID" ]; then
        # Only change to in-progress if not already done
        CURRENT=$("$PROG_BIN" issue show "$ISSUE_ID" --format=status 2>/dev/null || echo "")
        if [ "$CURRENT" != "done" ]; then
            "$PROG_BIN" issue status "$ISSUE_ID" progress 2>/dev/null || true
        fi
    fi
done

exit 0
"#
    .to_string()
}

/// Parse commit message and extract issue references
pub fn parse_issue_references(message: &str) -> Vec<IssueReference> {
    use regex::Regex;

    let mut refs = Vec::new();

    // Pattern for close/fix/resolve keywords
    let close_re = Regex::new(r"(?i)(closes?|fix(?:es)?|resolves?)\s*#([a-zA-Z0-9-]+)").unwrap();
    for cap in close_re.captures_iter(message) {
        refs.push(IssueReference {
            issue_id: cap[2].to_string(),
            action: IssueAction::Close,
        });
    }

    // Pattern for refs/see/re keywords
    let ref_re = Regex::new(r"(?i)(refs?|see|re)\s*#([a-zA-Z0-9-]+)").unwrap();
    for cap in ref_re.captures_iter(message) {
        refs.push(IssueReference {
            issue_id: cap[2].to_string(),
            action: IssueAction::Reference,
        });
    }

    // Bare references (just #ID without keyword) - filter out already captured
    // Use word boundary (\b) since look-behind isn't supported
    let bare_re = Regex::new(r"(?:^|[\s,;(])#([a-zA-Z0-9-]+)").unwrap();
    let already_captured: Vec<_> = refs.iter().map(|r| r.issue_id.clone()).collect();
    for cap in bare_re.captures_iter(message) {
        let id = cap[1].to_string();
        if !already_captured.contains(&id) {
            refs.push(IssueReference {
                issue_id: id,
                action: IssueAction::Mention,
            });
        }
    }

    refs
}

/// Issue reference found in commit message
#[derive(Debug, Clone)]
pub struct IssueReference {
    pub issue_id: String,
    pub action: IssueAction,
}

/// Action to take on an issue
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IssueAction {
    /// Close the issue (closes/fixes/resolves)
    Close,
    /// Mark as in-progress (refs/see/re)
    Reference,
    /// Just mention, no status change
    Mention,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_closes() {
        let refs = parse_issue_references("closes #123");
        assert_eq!(refs.len(), 1);
        assert_eq!(refs[0].issue_id, "123");
        assert_eq!(refs[0].action, IssueAction::Close);
    }

    #[test]
    fn test_parse_fixes() {
        let refs = parse_issue_references("Fixes #abc-123");
        assert_eq!(refs.len(), 1);
        assert_eq!(refs[0].issue_id, "abc-123");
        assert_eq!(refs[0].action, IssueAction::Close);
    }

    #[test]
    fn test_parse_refs() {
        let refs = parse_issue_references("refs #456");
        assert_eq!(refs.len(), 1);
        assert_eq!(refs[0].issue_id, "456");
        assert_eq!(refs[0].action, IssueAction::Reference);
    }

    #[test]
    fn test_parse_bare() {
        let refs = parse_issue_references("Working on #789");
        assert_eq!(refs.len(), 1);
        assert_eq!(refs[0].issue_id, "789");
        assert_eq!(refs[0].action, IssueAction::Mention);
    }

    #[test]
    fn test_parse_multiple() {
        let refs = parse_issue_references("closes #1, fixes #2, refs #3, see #4");
        assert_eq!(refs.len(), 4);
    }
}
